# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "django-dbbackup" = super.buildPythonPackage rec {
    pname = "django-dbbackup";
    version = "4.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/56/269824e8ae46772c3506c72ece58148f13e65a2ffaed42c5bd428960a729/django_dbbackup-4.2.1-py3-none-any.whl";
      sha256 = "1k883zmxgs8yz40qgw3l1niaiaj995cln6qvg35801xd1rh6acmj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pytz"
    ];
  };
  "django-error-report-2" = super.buildPythonPackage rec {
    pname = "django-error-report-2";
    version = "0.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/df/b0985db6c0e3feadf054b3f2c9df281d8eb7463a32a903a549ae21233eb7/django_error_report_2-0.4.2-py3-none-any.whl";
      sha256 = "06vc5z37n60fl1p7k42kkl51af0qa08gkfjzkylpx6zhg94rrn8x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-flags" = super.buildPythonPackage rec {
    pname = "django-flags";
    version = "5.0.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/05/7715921dc6599eb2f40f68b85975ae6567e4325b949e29701eb380d9d37f/django_flags-5.0.13-py2.py3-none-any.whl";
      sha256 = "0hkaq2iqnbkg3agih5p0x4kz382viav2dbch450cpxckdnw79psj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-ical" = super.buildPythonPackage rec {
    pname = "django-ical";
    version = "1.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/3f/647857462fa4169cb855aaf14969a6843f3910a3781d7c17f18c460b0e08/django_ical-1.9.2-py3-none-any.whl";
      sha256 = "0w6y24n94jjlvk7sd67nm69a4fiw1wjxgji006h92pvk0p56p8bl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-recurrence"
      self."icalendar"
    ];
  };
  "django-markdownify" = super.buildPythonPackage rec {
    pname = "django-markdownify";
    version = "0.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/35/c7a4bd957b279a8e7c808116bed399b73874ed3da78689993ee76f30d9f6/django_markdownify-0.9.5-py3-none-any.whl";
      sha256 = "11myjk68jw2ympax52ikbnc3aignfhdymsgmr99r883c717f8jic";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bleach"
      self."django"
      self."markdown"
    ];
  };
  "django-money" = super.buildPythonPackage rec {
    pname = "django-money";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/b1/9e8d1d48378d17f03cd2a9b11f705e05bc3a4b90c5b43e82b8cf91538098/django_money-3.2.0-py3-none-any.whl";
      sha256 = "0nalc9z5k63vyx10vx80zwjwabqf4mfgzwvfnl3ayxbi803gk69h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."py-moneyed"
      self."setuptools"
    ];
  };
  "django-q-sentry" = super.buildPythonPackage rec {
    pname = "django-q-sentry";
    version = "0.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/2e/7efdeff904400fba89428438c21ef3617c31544b17adbc17f4856b42369d/django_q_sentry-0.1.6-py3-none-any.whl";
      sha256 = "0l6hz1p1gr5ivd4qhp7lgs5hg0zakl6sphpj8yd7sfi5mmzlv2wv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sentry-sdk"
    ];
  };
  "django-q2" = super.buildPythonPackage rec {
    pname = "django-q2";
    version = "1.7.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/51/3d06afc0bd43769b300424cb7a34dd504b01900f7ff6bfc5229905145fbb/django_q2-1.7.4-py3-none-any.whl";
      sha256 = "07v7w995hlvm0l4ag7pf42zmsvvjvqfsqkkcpigfw8jqa1b6vnkf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-picklefield"
      self."importlib-metadata"
    ];
  };
  "django-recurrence" = super.buildPythonPackage rec {
    pname = "django-recurrence";
    version = "1.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/0a/5dc0f1f408a5b5f00c64ec57f3868248ed65ee660980118867b1279eca96/django_recurrence-1.11.1-py3-none-any.whl";
      sha256 = "1iaby5csbbakly848rr89y4mag52mlnrbdmsm49mi6srf84g6r8c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."python-dateutil"
    ];
  };
  "django-sql-utils" = super.buildPythonPackage rec {
    pname = "django-sql-utils";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/59/a5354087ece4b22465f9a31458ec182d1d54305994ecd6cc8bd8eedd7e43/django_sql_utils-0.7.0-py3-none-any.whl";
      sha256 = "0cm5jpbscfyd71j005jsjmccjgsj1givcd9yygy60sw94v441z7y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."sqlparse"
    ];
  };
  "django-sslserver" = super.buildPythonPackage rec {
    pname = "django-sslserver";
    version = "0.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/97/e4011f3944f83a7d2aaaf893c3689ad70e8d2ae46fb6e14fd0e3b0c6ce0b/django_sslserver-0.22-py3-none-any.whl";
      sha256 = "1ia754fg55i8997bg9d38y70xy3k165kvnwdq0hj9p6cs9is7665";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-stdimage" = super.buildPythonPackage rec {
    pname = "django-stdimage";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/e4/f90e895cb97bd625c9d162dc7919addd6321d34023439623abb6e4c99f30/django_stdimage-6.0.2-py2.py3-none-any.whl";
      sha256 = "1j11spri5qd7i3xw97abprfr6r3ivddjs0rb1rc7906493dgfwws";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pillow"
    ];
  };
  "django-structlog" = super.buildPythonPackage rec {
    pname = "django-structlog";
    version = "8.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/b2/a52adecee4c7d4f728f47df96f6149cdcf9425154e2efee8c9c3664b6a18/django_structlog-8.1.0-py3-none-any.whl";
      sha256 = "051jb994d2pvq3ndmzl924q98vn4q4qpngl9m4xqsvpksr5mcwhh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asgiref"
      self."django"
      self."django-ipware"
      self."structlog"
    ];
  };
  "django-user-sessions" = super.buildPythonPackage rec {
    pname = "django-user-sessions";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/f4/fab7937669540636bacd421cf30adbbfa8dc41a2f84f175e8fc133907776/django_user_sessions-2.0.0-py3-none-any.whl";
      sha256 = "0j3pqsf5ksmjhjz1s041qnxlbbmk13x0jmlnc9qb8mpmg515ar89";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-weasyprint" = super.buildPythonPackage rec {
    pname = "django-weasyprint";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/8e/f2f3e038c74dbdd514261268b7a645180cdb23a7a35d6c9938014622dc6d/django_weasyprint-2.3.0-py3-none-any.whl";
      sha256 = "0da751kkplzz0cc3ad9j6pz06q98f2farqmvr2bks4ijcfqv6z40";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."weasyprint"
    ];
  };
  "django-xforwardedfor-middleware" = super.buildPythonPackage rec {
    pname = "django-xforwardedfor-middleware";
    version = "2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/79/a770c32c1927720cf44e48ac6adb70986253e83d3948c1e5fd152e432db7/django-xforwardedfor-middleware-2.0.tar.gz";
      sha256 = "090b1x25rv0lksv5a4ksy9v4lcxpn6pl62rydwdm999kgyr1rz8n";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "pip-licenses" = super.buildPythonPackage rec {
    pname = "pip-licenses";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/0a/bfaf1479d09d19f503a669d9c8e433ac59ae687fb8da1d8207eb85c5a9f4/pip_licenses-5.0.0-py3-none-any.whl";
      sha256 = "0za71vsaq29gvwcc52b61nqkwhbkna55qh0wmz8qdyryfmk3dj42";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."prettytable"
      self."tomli"
    ];
  };
  "py-moneyed" = super.buildPythonPackage rec {
    pname = "py-moneyed";
    version = "3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/2b/2d87f12edc70f0d8c85148c51b57a4b8cf89e4d8ad291935a47ed1b7c52e/py_moneyed-3.0-py3-none-any.whl";
      sha256 = "1fyrfqv76zpwkkp5x2pw7623rdz90r91in4kc4clcny0k57s30wm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."babel"
      self."typing-extensions"
    ];
  };
}
