{ ps }:
with ps; [
  asgiref
  async-timeout
  attrs
  babel
  bleach
  brotli
  certifi
  cffi
  charset-normalizer
  coreapi
  coreschema
  cryptography
  cssselect2
  defusedxml
  deprecated
  diff-match-patch
  dj-rest-auth
  django
  django-allauth
  django-allauth-2fa
  django-cleanup
  django-cors-headers
  django-crispy-forms
  django-dbbackup
  django-error-report-2
  django-filter
  django-flags
  django-formtools
  django-ical
  django-import-export
  django-ipware
  django-js-asset
  django-maintenance-mode
  django-markdownify
  django-money
  django-mptt
  django-otp
  django-picklefield
  django-q-sentry
  django-q2
  django-recurrence
  django-redis
  django-sesame
  django-sql-utils
  django-sslserver
  django-stdimage
  django-structlog
  django-taggit
  django-user-sessions
  django-weasyprint
  django-xforwardedfor-middleware
  djangorestframework
  djangorestframework-simplejwt
  drf-spectacular
  dulwich
  et-xmlfile
  feedparser
  flexcache
  flexparser
  fonttools
  googleapis-common-protos
  grpcio
  gunicorn
  html5lib
  icalendar
  idna
  importlib-metadata
  inflection
  isodate
  itypes
  jinja2
  jsonschema
  jsonschema-specifications
  lxml
  markdown
  markuppy
  markupsafe
  odfpy
  openpyxl
  opentelemetry-api
  opentelemetry-exporter-otlp
  opentelemetry-exporter-otlp-proto-common
  opentelemetry-exporter-otlp-proto-grpc
  opentelemetry-exporter-otlp-proto-http
  opentelemetry-instrumentation
  opentelemetry-instrumentation-django
  opentelemetry-instrumentation-redis
  opentelemetry-instrumentation-requests
  opentelemetry-instrumentation-wsgi
  opentelemetry-proto
  opentelemetry-sdk
  opentelemetry-semantic-conventions
  opentelemetry-util-http
  packaging
  pdf2image
  pillow
  pint
  pip-licenses
  platformdirs
  prettytable
  protobuf
  py-moneyed
  pycparser
  pydyf
  pyjwt
  pyphen
  python-barcode
  python-dateutil
  python-dotenv
  python-fsutil
  python-ipware
  python3-openid
  python3-saml
  pytz
  pyyaml
  qrcode
  rapidfuzz
  redis
  referencing
  requests
  rpds-py
  sentry-sdk
  setuptools
  sgmllib3k
  six
  sqlparse
  structlog
  tablib
  tinycss2
  tomli
  typing-extensions
  tzdata
  uritemplate
  urllib3
  wcwidth
  weasyprint
  webencodings
  whitenoise
  wrapt
  xlrd
  xlwt
  xmlsec
  zipp
  zopfli
]