# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "asgiref" = super.buildPythonPackage rec {
    pname = "asgiref";
    version = "3.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/e3/893e8757be2612e6c266d9bb58ad2e3651524b5b40cf56761e985a28b13e/asgiref-3.8.1-py3-none-any.whl";
      sha256 = "0isy6f816ir6i2jp5vka3nxq4px5ny36djzjri9gwclqhk63w7iy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "5.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ba/e2081de779ca30d473f21f5b30e0e737c438205440784c7dfc81efc2b029/async_timeout-5.0.1-py3-none-any.whl";
      sha256 = "0v77gzkjk90zg9d41jfap9j86v09bssrh8zcax2kb1gzcsaq1qrr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "24.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6a/21/5b6702a7f963e95456c0de2d495f67bf5fd62840ac655dc451586d23d39a/attrs-24.2.0-py3-none-any.whl";
      sha256 = "1qpdcwcaw7h1bpizarlkimhaq9yx0j0n36f1b211q6g3dnwix4l1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "babel" = super.buildPythonPackage rec {
    pname = "babel";
    version = "2.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/20/bc79bc575ba2e2a7f70e8a1155618bb1301eaa5132a8271373a6903f73f8/babel-2.16.0-py3-none-any.whl";
      sha256 = "12zs6p2caf447r0q8ibxfqvqp4qc4k1r2qv9yvdbf1kwnfc5p2rn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "bleach" = super.buildPythonPackage rec {
    pname = "bleach";
    version = "6.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/55/96142937f66150805c25c4d0f31ee4132fd33497753400734f9dfdcbdc66/bleach-6.2.0-py3-none-any.whl";
      sha256 = "0phyydixsbs39vd59x9nczgjbqgibz9xiz3qslpx5hx7jxh9qz8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."tinycss2"
      self."webencodings"
    ];
  };
  "brotli" = super.buildPythonPackage rec {
    pname = "brotli";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/c2/f9e977608bdf958650638c3f1e28f85a1b075f075ebbe77db8555463787b/Brotli-1.1.0.tar.gz";
      sha256 = "0937aii66rqbin9190v9hazx6rqbq08kdha0wi0mif5w26n0ipl1";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2024.8.30";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/12/90/3c9ff0512038035f59d279fddeb79f5f1eccd8859f06d6163c58798b9487/certifi-2024.8.30-py3-none-any.whl";
      sha256 = "1n1h68zgyica9zikf1yq0dcj8dflcrr5jgyszdzjb9xp7nsj0a4j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.17.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/97/c783634659c2920c3fc70419e3af40972dbaf758daa229a7d6ea6135c90d/cffi-1.17.1.tar.gz";
      sha256 = "0918qn4yfjfgcy7i4imfy9q1cvl3svmm06anakflig1jdh0wcf8w";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/4f/e1808dc01273379acc506d18f1504eb2d299bd4131743b9fc54d7be4df1e/charset_normalizer-3.4.0.tar.gz";
      sha256 = "0gp9v9wr0wgmjdnzhq91ny8va3zbqbqv6clhwb2klb7qsk1ifci2";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "coreapi" = super.buildPythonPackage rec {
    pname = "coreapi";
    version = "2.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/3a/9dedaad22962770edd334222f2b3c3e7ad5e1c8cab1d6a7992c30329e2e5/coreapi-2.3.3-py2.py3-none-any.whl";
      sha256 = "1wz65vsnr9i6fz0qx6m2m6xq1bb3dxkfbvgr1pqp3qfksqcd2fdz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."coreschema"
      self."itypes"
      self."requests"
      self."uritemplate"
    ];
  };
  "coreschema" = super.buildPythonPackage rec {
    pname = "coreschema";
    version = "0.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/08/1d105a70104e078718421e6c555b8b293259e7fc92f7e9a04869947f198f/coreschema-0.0.4.tar.gz";
      sha256 = "01qn9bfkklpjkr0zn6bd5fr372n1jd5p455scw4ap0nl0xh500wm";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
    ];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "43.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/05/07b55d1fa21ac18c3a8c79f764e2514e6f6a9698f1be44994f5adf0d29db/cryptography-43.0.3.tar.gz";
      sha256 = "01d8anh4crjvpa0s044rxkdi9cjnz4w15dj3yipjljba4q0r0nri";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "cssselect2" = super.buildPythonPackage rec {
    pname = "cssselect2";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/3a/e39436efe51894243ff145a37c4f9a030839b97779ebcc4f13b3ba21c54e/cssselect2-0.7.0-py3-none-any.whl";
      sha256 = "0sarkfj638m75ir1vi2lwdhr5hl6nbv73z027y8raia4zmdsc8zx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."tinycss2"
      self."webencodings"
    ];
  };
  "defusedxml" = super.buildPythonPackage rec {
    pname = "defusedxml";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl";
      sha256 = "0qca37v5iv0304hrl9pzad4jpnxfrnv449cyi768c0kp53jfflm3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "deprecated" = super.buildPythonPackage rec {
    pname = "deprecated";
    version = "1.2.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/8f/c7f227eb42cfeaddce3eb0c96c60cbca37797fa7b34f8e1aeadf6c5c0983/Deprecated-1.2.15-py2.py3-none-any.whl";
      sha256 = "080kn9svkq61vjn57zb5kw3w3pi5kkc4kcys1n09dz2bmjlc8frm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wrapt"
    ];
  };
  "diff-match-patch" = super.buildPythonPackage rec {
    pname = "diff-match-patch";
    version = "20241021";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f7/bb/2aa9b46a01197398b901e458974c20ed107935c26e44e37ad5b0e5511e44/diff_match_patch-20241021-py3-none-any.whl";
      sha256 = "10k7jcc8hwh7v9mj4a28wr639pahvwb5xpmhh78w0awbzcrs7klk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "dj-rest-auth" = super.buildPythonPackage rec {
    pname = "dj-rest-auth";
    version = "7.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/e5/6cab919e53c4981542e2090249a05278959840cffaf43a272d6ce204b53a/dj-rest-auth-7.0.0.tar.gz";
      sha256 = "0vpqw7m9lcks9k4cvxv9m8hyghmyf5x2vg2rkzd74f126lxc1nq8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."djangorestframework"
    ];
  };
  "django" = super.buildPythonPackage rec {
    pname = "django";
    version = "4.2.17";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/85/457360cb3de496382e35db4c2af054066df5c40e26df31400d0109a0500c/Django-4.2.17-py3-none-any.whl";
      sha256 = "1q4dp88iwkrpa4srnl1wzbdyfwqmqs30fp04siwg29ds2h13b4rs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asgiref"
      self."sqlparse"
    ];
  };
  "django-allauth" = super.buildPythonPackage rec {
    pname = "django-allauth";
    version = "65.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/df/1db5a3d7c87df36c4258ad58502dc12971df28a3b9c1e0be2e41007a7277/django_allauth-65.2.0.tar.gz";
      sha256 = "0vwbwrxrmz0mblj3n6ikyhy47rzc4qn305kk0bl6zzgfgfppng8a";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
    ];
    propagatedBuildInputs = [
      self."asgiref"
      self."django"
      self."python3-openid"
      self."python3-saml"
    ];
  };
  "django-allauth-2fa" = super.buildPythonPackage rec {
    pname = "django-allauth-2fa";
    version = "0.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/3f/7befd3d8fe169971cddb79eaf74e4bc6215cfef152bc772418d1cd800f6e/django_allauth_2fa-0.11.1-py3-none-any.whl";
      sha256 = "1xmymqgyll7awhz6win3m6p6rsdbymhv104pwm2ssrlg93fn2b9g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-allauth"
      self."django-otp"
      self."qrcode"
    ];
  };
  "django-cleanup" = super.buildPythonPackage rec {
    pname = "django-cleanup";
    version = "9.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/d7/a83dc87c2383e125da29948f7bccf5b30126c087a5a831316482407a960f/django_cleanup-9.0.0-py3-none-any.whl";
      sha256 = "0348mm0awixsh36a6gpyibsa0wj684gih5rvd07rygr363lb1y0r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "django-cors-headers" = super.buildPythonPackage rec {
    pname = "django-cors-headers";
    version = "4.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/73/689532cf164ab10ed1521d825ea156656520cec98886c8d2ac1ce8829220/django_cors_headers-4.6.0-py3-none-any.whl";
      sha256 = "18wbsksn675jadpzn9nqir5m7ikqn79ma00f2paj8731gr4w1nwf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asgiref"
      self."django"
    ];
  };
  "django-crispy-forms" = super.buildPythonPackage rec {
    pname = "django-crispy-forms";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/34/f5240bcecb9c0d87fc339edf66f87d2ca5580e995ca966a93fdfb5ba7a66/django_crispy_forms-1.14.0-py3-none-any.whl";
      sha256 = "010680x1rh6vqhn8fn44x1jms7wx0b1jlidwq0wjsq6yyqvj0kdw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "django-dbbackup" = super.buildPythonPackage rec {
    pname = "django-dbbackup";
    version = "4.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/56/269824e8ae46772c3506c72ece58148f13e65a2ffaed42c5bd428960a729/django_dbbackup-4.2.1-py3-none-any.whl";
      sha256 = "1k883zmxgs8yz40qgw3l1niaiaj995cln6qvg35801xd1rh6acmj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pytz"
    ];
  };
  "django-error-report-2" = super.buildPythonPackage rec {
    pname = "django-error-report-2";
    version = "0.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/df/b0985db6c0e3feadf054b3f2c9df281d8eb7463a32a903a549ae21233eb7/django_error_report_2-0.4.2-py3-none-any.whl";
      sha256 = "06vc5z37n60fl1p7k42kkl51af0qa08gkfjzkylpx6zhg94rrn8x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-filter" = super.buildPythonPackage rec {
    pname = "django-filter";
    version = "24.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/b1/92f1c30b47c1ebf510c35a2ccad9448f73437e5891bbd2b4febe357cc3de/django_filter-24.3-py3-none-any.whl";
      sha256 = "0r6w97fh4sziyi7jpsqav2ig2x1m9djcvz5wk6v7zqccj8i2i1f4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-flags" = super.buildPythonPackage rec {
    pname = "django-flags";
    version = "5.0.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/05/7715921dc6599eb2f40f68b85975ae6567e4325b949e29701eb380d9d37f/django_flags-5.0.13-py2.py3-none-any.whl";
      sha256 = "0hkaq2iqnbkg3agih5p0x4kz382viav2dbch450cpxckdnw79psj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-formtools" = super.buildPythonPackage rec {
    pname = "django-formtools";
    version = "2.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/12/63/91a107e3aaaf3987bad036494dfd8cc2675f4a66d22e65ffd6711f84ba70/django_formtools-2.5.1-py3-none-any.whl";
      sha256 = "06kngs7brz1ydj6z1zy20ykx3b2syyf69k31d7pixk2jv97bdsdw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-ical" = super.buildPythonPackage rec {
    pname = "django-ical";
    version = "1.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/3f/647857462fa4169cb855aaf14969a6843f3910a3781d7c17f18c460b0e08/django_ical-1.9.2-py3-none-any.whl";
      sha256 = "0w6y24n94jjlvk7sd67nm69a4fiw1wjxgji006h92pvk0p56p8bl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-recurrence"
      self."icalendar"
    ];
  };
  "django-import-export" = super.buildPythonPackage rec {
    pname = "django-import-export";
    version = "3.3.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/06/2b474ddf52d5e2e46ea821789de6a76bc50996f0a592fdd29af1891d20af/django_import_export-3.3.9-py3-none-any.whl";
      sha256 = "00xi95gzbw39bj7ic0682nv9dlfp5dagprwjlcvvvlfniv0anv6x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."diff-match-patch"
      self."django"
      self."tablib"
    ];
  };
  "django-ipware" = super.buildPythonPackage rec {
    pname = "django-ipware";
    version = "7.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/33/bf539925b102d68200da5b1d3eacb8aa5d5d9a065972e8b8724d0d53bb0d/django_ipware-7.0.1-py2.py3-none-any.whl";
      sha256 = "02a7ys8xr6s8xgma8qb77kq50n68c022gr3qyvkilrhgjbpbn5nv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."python-ipware"
    ];
  };
  "django-js-asset" = super.buildPythonPackage rec {
    pname = "django-js-asset";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/4d/5bb8c351f2515a616576a4218c736af081edf0dd4d1eead1c7e880f74c0e/django_js_asset-2.2.0-py3-none-any.whl";
      sha256 = "1n1hmv06nd8k9sz0krzl5ks0crz7n5iflvmmk43z21ixw5cfiwvy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-maintenance-mode" = super.buildPythonPackage rec {
    pname = "django-maintenance-mode";
    version = "0.21.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/7b/b4d648a9fe8d450dd55e10527fbbb37d2c16dc366c9b7fa67b103404cd29/django_maintenance_mode-0.21.1-py3-none-any.whl";
      sha256 = "156vq6idb5nacliplam29l0k9binsfhd6ya4nlm8nzvb707gyby0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."python-fsutil"
    ];
  };
  "django-markdownify" = super.buildPythonPackage rec {
    pname = "django-markdownify";
    version = "0.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/35/c7a4bd957b279a8e7c808116bed399b73874ed3da78689993ee76f30d9f6/django_markdownify-0.9.5-py3-none-any.whl";
      sha256 = "11myjk68jw2ympax52ikbnc3aignfhdymsgmr99r883c717f8jic";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bleach"
      self."django"
      self."markdown"
    ];
  };
  "django-money" = super.buildPythonPackage rec {
    pname = "django-money";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/b1/9e8d1d48378d17f03cd2a9b11f705e05bc3a4b90c5b43e82b8cf91538098/django_money-3.2.0-py3-none-any.whl";
      sha256 = "0nalc9z5k63vyx10vx80zwjwabqf4mfgzwvfnl3ayxbi803gk69h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."py-moneyed"
      self."setuptools"
    ];
  };
  "django-mptt" = super.buildPythonPackage rec {
    pname = "django-mptt";
    version = "0.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/27/61a39b0d716e52be2df7d9fed6e35fe10eb3faaf207cdfaac3f9f68ecb1a/django_mptt-0.16.0-py3-none-any.whl";
      sha256 = "1dgk59yp7byvj2v7512z37wgs7swl0ihkv80w7i9939ilfdq85l7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django-js-asset"
    ];
  };
  "django-otp" = super.buildPythonPackage rec {
    pname = "django-otp";
    version = "1.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0a/73/92ae49259cb779a27280caeae11871f5f9dfb29c9d3fc520a635a47895c8/django_otp-1.5.4-py3-none-any.whl";
      sha256 = "1nv60di9snnabhbq8yj2mxjyckjq8fa86wvg6g6zbsn0k9kflgbq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-picklefield" = super.buildPythonPackage rec {
    pname = "django-picklefield";
    version = "3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/f9/1502538efa2d4cd3a88ff806cdbd08b1c681dd828d05b6dbc8bcb50a8586/django_picklefield-3.2-py3-none-any.whl";
      sha256 = "0k3njw2a49n044cd9gldyjgiirc2rf5v239jv4jrixhhs4wkb9z9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-q-sentry" = super.buildPythonPackage rec {
    pname = "django-q-sentry";
    version = "0.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/2e/7efdeff904400fba89428438c21ef3617c31544b17adbc17f4856b42369d/django_q_sentry-0.1.6-py3-none-any.whl";
      sha256 = "0l6hz1p1gr5ivd4qhp7lgs5hg0zakl6sphpj8yd7sfi5mmzlv2wv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sentry-sdk"
    ];
  };
  "django-q2" = super.buildPythonPackage rec {
    pname = "django-q2";
    version = "1.7.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/51/3d06afc0bd43769b300424cb7a34dd504b01900f7ff6bfc5229905145fbb/django_q2-1.7.4-py3-none-any.whl";
      sha256 = "07v7w995hlvm0l4ag7pf42zmsvvjvqfsqkkcpigfw8jqa1b6vnkf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-picklefield"
      self."importlib-metadata"
    ];
  };
  "django-recurrence" = super.buildPythonPackage rec {
    pname = "django-recurrence";
    version = "1.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/0a/5dc0f1f408a5b5f00c64ec57f3868248ed65ee660980118867b1279eca96/django_recurrence-1.11.1-py3-none-any.whl";
      sha256 = "1iaby5csbbakly848rr89y4mag52mlnrbdmsm49mi6srf84g6r8c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."python-dateutil"
    ];
  };
  "django-redis" = super.buildPythonPackage rec {
    pname = "django-redis";
    version = "5.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/f1/63caad7c9222c26a62082f4f777de26389233b7574629996098bf6d25a4d/django_redis-5.4.0-py3-none-any.whl";
      sha256 = "0nyx5saa5abcvb3g979ii6zh8qn94vsgg1wrmzi341w1vbvqvj7b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."redis"
    ];
  };
  "django-sesame" = super.buildPythonPackage rec {
    pname = "django-sesame";
    version = "3.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/e7/951f35106972668b61e79635c93933c51c2d58f49a9c8ebf0a8ff7262331/django_sesame-3.2.2-py3-none-any.whl";
      sha256 = "1xbcd2yrdx4bvizjfvnarl8pxwyqdy5vf99g4ry8k3720i6vsgjj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-sql-utils" = super.buildPythonPackage rec {
    pname = "django-sql-utils";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/59/a5354087ece4b22465f9a31458ec182d1d54305994ecd6cc8bd8eedd7e43/django_sql_utils-0.7.0-py3-none-any.whl";
      sha256 = "0cm5jpbscfyd71j005jsjmccjgsj1givcd9yygy60sw94v441z7y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."sqlparse"
    ];
  };
  "django-sslserver" = super.buildPythonPackage rec {
    pname = "django-sslserver";
    version = "0.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/97/e4011f3944f83a7d2aaaf893c3689ad70e8d2ae46fb6e14fd0e3b0c6ce0b/django_sslserver-0.22-py3-none-any.whl";
      sha256 = "1ia754fg55i8997bg9d38y70xy3k165kvnwdq0hj9p6cs9is7665";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-stdimage" = super.buildPythonPackage rec {
    pname = "django-stdimage";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/e4/f90e895cb97bd625c9d162dc7919addd6321d34023439623abb6e4c99f30/django_stdimage-6.0.2-py2.py3-none-any.whl";
      sha256 = "1j11spri5qd7i3xw97abprfr6r3ivddjs0rb1rc7906493dgfwws";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pillow"
    ];
  };
  "django-structlog" = super.buildPythonPackage rec {
    pname = "django-structlog";
    version = "8.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/b2/a52adecee4c7d4f728f47df96f6149cdcf9425154e2efee8c9c3664b6a18/django_structlog-8.1.0-py3-none-any.whl";
      sha256 = "051jb994d2pvq3ndmzl924q98vn4q4qpngl9m4xqsvpksr5mcwhh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asgiref"
      self."django"
      self."django-ipware"
      self."structlog"
    ];
  };
  "django-taggit" = super.buildPythonPackage rec {
    pname = "django-taggit";
    version = "6.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6b/34/4185c345530b91d05cb82e05d07148f481a5eb5dc2ac44e092b3daa6f206/django_taggit-6.1.0-py3-none-any.whl";
      sha256 = "1w2cdsal32qkp4ns9hr1plqphib2942zj6wywkbv6v67pdj64xxb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-user-sessions" = super.buildPythonPackage rec {
    pname = "django-user-sessions";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/f4/fab7937669540636bacd421cf30adbbfa8dc41a2f84f175e8fc133907776/django_user_sessions-2.0.0-py3-none-any.whl";
      sha256 = "0j3pqsf5ksmjhjz1s041qnxlbbmk13x0jmlnc9qb8mpmg515ar89";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-weasyprint" = super.buildPythonPackage rec {
    pname = "django-weasyprint";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/8e/f2f3e038c74dbdd514261268b7a645180cdb23a7a35d6c9938014622dc6d/django_weasyprint-2.3.0-py3-none-any.whl";
      sha256 = "0da751kkplzz0cc3ad9j6pz06q98f2farqmvr2bks4ijcfqv6z40";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."weasyprint"
    ];
  };
  "django-xforwardedfor-middleware" = super.buildPythonPackage rec {
    pname = "django-xforwardedfor-middleware";
    version = "2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/79/a770c32c1927720cf44e48ac6adb70986253e83d3948c1e5fd152e432db7/django-xforwardedfor-middleware-2.0.tar.gz";
      sha256 = "090b1x25rv0lksv5a4ksy9v4lcxpn6pl62rydwdm999kgyr1rz8n";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "djangorestframework" = super.buildPythonPackage rec {
    pname = "djangorestframework";
    version = "3.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/4b/3b46c0914ba4b7546a758c35fdfa8e7f017fcbe7f23c878239e93623337a/djangorestframework-3.14.0-py3-none-any.whl";
      sha256 = "027x0g8lrbwsvvd7ym1m3m7fsa7ma43sf5sd0ryim3i1ky6gaqzb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pytz"
    ];
  };
  "djangorestframework-simplejwt" = super.buildPythonPackage rec {
    pname = "djangorestframework-simplejwt";
    version = "5.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/ab/88f73cf08d2ad3fb9f71b956dceca5680a57f121e5ce9a604f365877d57e/djangorestframework_simplejwt-5.3.1-py3-none-any.whl";
      sha256 = "086ji161ch6lzwh4wxh9alkalpyl5bbjqiwxc82kk4a6m9kcj6rq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."django"
      self."djangorestframework"
      self."pyjwt"
    ];
  };
  "drf-spectacular" = super.buildPythonPackage rec {
    pname = "drf-spectacular";
    version = "0.27.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/cd/84c44a5d435f6544e58a9b138305f59bca232157ae4ecb658f9787f87d1c/drf_spectacular-0.27.2-py3-none-any.whl";
      sha256 = "0yy3gv7kacxiqdan1xrj9nx7ly6892j4wjs1b5pszgpvnbw4ph5i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."djangorestframework"
      self."inflection"
      self."jsonschema"
      self."pyyaml"
      self."typing-extensions"
      self."uritemplate"
    ];
  };
  "dulwich" = super.buildPythonPackage rec {
    pname = "dulwich";
    version = "0.22.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/b2/13367fe4b4cb187cf13823040403b37d167c967675d543451caa9e9d2589/dulwich-0.22.6.tar.gz";
      sha256 = "1d882hm1jhn417h5mpnq67cb92c6bf1ryy708g55kp55kxclvx61";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."urllib3"
    ];
  };
  "et-xmlfile" = super.buildPythonPackage rec {
    pname = "et-xmlfile";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl";
      sha256 = "1aic3cakdxgh6x8dhdy5hmy22i7yp1vlql5pqc13b12nqw5p54bs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "feedparser" = super.buildPythonPackage rec {
    pname = "feedparser";
    version = "6.0.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/d4/8c31aad9cc18f451c49f7f9cfb5799dadffc88177f7917bc90a66459b1d7/feedparser-6.0.11-py3-none-any.whl";
      sha256 = "0iddyj94kmb7xph39jgid48y3pi803xsmmmipsgb2wjm75xyxrqb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sgmllib3k"
    ];
  };
  "flexcache" = super.buildPythonPackage rec {
    pname = "flexcache";
    version = "0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/cd/c883e1a7c447479d6e13985565080e3fea88ab5a107c21684c813dba1875/flexcache-0.3-py3-none-any.whl";
      sha256 = "0cifrmnldw8i8rb1g826hc5kk1d16ffqsc2y27hgcsikhbm9yg6l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "flexparser" = super.buildPythonPackage rec {
    pname = "flexparser";
    version = "0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/5e/3be305568fe5f34448807976dc82fc151d76c3e0e03958f34770286278c1/flexparser-0.4-py3-none-any.whl";
      sha256 = "0ilq2w01vsc1niarkbznjc13q0i1fx24qchgc8akxjrd35bb8f1p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "fonttools" = super.buildPythonPackage rec {
    pname = "fonttools";
    version = "4.55.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d7/4e/053fe1b5c0ce346c0a9d0557492c654362bafb14f026eae0d3ee98009152/fonttools-4.55.0.tar.gz";
      sha256 = "0wfaza5qwhg71czvw5xdrpqi3mpaajr25jgfwzap4dbkmg3aqdkn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."brotli"
      self."zopfli"
    ];
  };
  "googleapis-common-protos" = super.buildPythonPackage rec {
    pname = "googleapis-common-protos";
    version = "1.66.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/0f/c0713fb2b3d28af4b2fded3291df1c4d4f79a00d15c2374a9e010870016c/googleapis_common_protos-1.66.0-py2.py3-none-any.whl";
      sha256 = "1vdqhbivfk69wjdhwdr7ir4hp6hidhgl0rj4yz4hwbmvz9swvayp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "grpcio" = super.buildPythonPackage rec {
    pname = "grpcio";
    version = "1.68.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/da/132615afbfc722df4bba963844843a205aa298fd5f9a03fa2995e8dddf11/grpcio-1.68.0.tar.gz";
      sha256 = "0fjl0kja3pvbqzz4khyz3h1lzbda47mfjwb6j2wxsksakg9q6x3y";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gunicorn" = super.buildPythonPackage rec {
    pname = "gunicorn";
    version = "23.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/7d/6dac2a6e1eba33ee43f318edbed4ff29151a49b5d37f080aad1e6469bca4/gunicorn-23.0.0-py3-none-any.whl";
      sha256 = "0kfa11wk2z259qwx65ymn3nx1blg5j5k5y6g33adzr0djlw0sh7c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
    ];
  };
  "html5lib" = super.buildPythonPackage rec {
    pname = "html5lib";
    version = "1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl";
      sha256 = "0784ivjj43phsnxav7wapza9w16p4q2sd1krwfgyjc62w7yzhy0d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
  };
  "icalendar" = super.buildPythonPackage rec {
    pname = "icalendar";
    version = "6.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/b5/276bf1e5d0433144b27f707c40afe79e7e8863806837f42956053840a078/icalendar-6.1.0-py3-none-any.whl";
      sha256 = "0sabf4icijsly68m9qhakljwhdaiq5nidjxgbm4lhsbf99vrph26";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."python-dateutil"
      self."tzdata"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl";
      sha256 = "1lw72a5swas501zvkpd6dsryj5hzjijqxs3526kbp7151md1jvcl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "8.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/d9/a1e041c5e7caa9a05c925f4bdbdfb7f006d1f74996af53467bc394c97be7/importlib_metadata-8.5.0-py3-none-any.whl";
      sha256 = "12x61a44fzs9y64dbyri45h2n0v7qpkra2z6b4apyylbsabl3ra5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "inflection" = super.buildPythonPackage rec {
    pname = "inflection";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/59/91/aa6bde563e0085a02a435aa99b49ef75b0a4b062635e606dab23ce18d720/inflection-0.5.1-py2.py3-none-any.whl";
      sha256 = "18m80mk55fd1p9dnl1zil1i9p5a2602kvb39vrdg791q15j2p2zk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "isodate" = super.buildPythonPackage rec {
    pname = "isodate";
    version = "0.7.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/aa/0aca39a37d3c7eb941ba736ede56d689e7be91cab5d9ca846bde3999eba6/isodate-0.7.2-py3-none-any.whl";
      sha256 = "05cyv736dn8nw7n7qna3nlb2hd7d17afdz30061m8403v0vrj018";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "itypes" = super.buildPythonPackage rec {
    pname = "itypes";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/bb/3bd99c7cd34d4a123b2903e16da364f6d2078b1c3a3530a8ad105c668104/itypes-1.2.0-py2.py3-none-any.whl";
      sha256 = "1ih4vn34q6abk83j72xl1pw91x08sjr74dkpcbprmll9r9r6inh3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/80/3a54838c3fb461f6fec263ebf3a3a41771bd05190238de3486aae8540c36/jinja2-3.1.4-py3-none-any.whl";
      sha256 = "0z8r4myrqvwwr3kcz1zlyhwqqcg7lbk17a5pcyak3997nymx4pdw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markupsafe"
    ];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "4.23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/4a/4f9dbeb84e8850557c02365a0eee0649abe5eb1d84af92a25731c6c0f922/jsonschema-4.23.0-py3-none-any.whl";
      sha256 = "0rjmzpvsr9sn7xiph4hs8583w50xa2abm28bkz7zia24n7wbdbgv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."jsonschema-specifications"
      self."referencing"
      self."rpds-py"
    ];
  };
  "jsonschema-specifications" = super.buildPythonPackage rec {
    pname = "jsonschema-specifications";
    version = "2024.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/0f/8910b19ac0670a0f80ce1008e5e751c4a57e14d2c4c13a482aa6079fa9d6/jsonschema_specifications-2024.10.1-py3-none-any.whl";
      sha256 = "1gx9bm3ngsnyydamn3wx4d4zaya44fni4p7hxjhdjmv3c600d6m0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."referencing"
    ];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "5.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/6b/20c3a4b24751377aaa6307eb230b66701024012c29dd374999cc92983269/lxml-5.3.0.tar.gz";
      sha256 = "0vwcxi8rxxdaahxf0mb8n5aqyfyw0lck9gndc2nc3phy1nirq42f";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "markdown" = super.buildPythonPackage rec {
    pname = "markdown";
    version = "3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/08/83871f3c50fc983b88547c196d11cf8c3340e37c32d2e9d6152abe2c61f7/Markdown-3.7-py3-none-any.whl";
      sha256 = "00y8n5vkm73f333cn86zg5p9b3lksbx9fb4r89wis6mqj1bdzdky";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
  "markuppy" = super.buildPythonPackage rec {
    pname = "markuppy";
    version = "1.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/ca/f43541b41bd17fc945cfae7ea44f1661dc21ea65ecc944a6fa138eead94c/MarkupPy-1.14.tar.gz";
      sha256 = "0pqdmpxbr8iq22b4css2gz5z6s01ddpzyj25x27kgbs2lp0f5phs";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "markupsafe" = super.buildPythonPackage rec {
    pname = "markupsafe";
    version = "3.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/97/5d42485e71dfc078108a86d6de8fa46db44a1a9295e89c5d6d4a06e23a62/markupsafe-3.0.2.tar.gz";
      sha256 = "1w1b1a5pskpqhx1mb53rgpv9srplhrrkr4hsl67f8rq1z3nx6mgf";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "odfpy" = super.buildPythonPackage rec {
    pname = "odfpy";
    version = "1.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/73/8ade73f6749177003f7ce3304f524774adda96e6aaab30ea79fd8fda7934/odfpy-1.4.1.tar.gz";
      sha256 = "1v1qqk9p12qla85yscq2g413l3qasn6yr4ncyc934465b5p6lxnv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."defusedxml"
    ];
  };
  "openpyxl" = super.buildPythonPackage rec {
    pname = "openpyxl";
    version = "3.1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl";
      sha256 = "1qlxqyfhgwsycsxkp0k0xb843bxg5707sqgl4pwfxzvv20mw30jj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."et-xmlfile"
    ];
  };
  "opentelemetry-api" = super.buildPythonPackage rec {
    pname = "opentelemetry-api";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/58/b17393cdfc149e14ee84c662abf921993dcce8058628359ef1f49e2abb97/opentelemetry_api-1.28.2-py3-none-any.whl";
      sha256 = "19km88nhsz1b999ryywpplsaj1f7r2ismb5iws7jbssv4sgcikkg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deprecated"
      self."importlib-metadata"
    ];
  };
  "opentelemetry-exporter-otlp" = super.buildPythonPackage rec {
    pname = "opentelemetry-exporter-otlp";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b8/16/65b0f0f9a85e6c0e1ce30e0ea96e0174ca4db85301883d1d6a9702700946/opentelemetry_exporter_otlp-1.28.2-py3-none-any.whl";
      sha256 = "0w2z8m43lpd0xrn25mh4lxp11ypchv20ldkgwclx7g76h156s3xm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-exporter-otlp-proto-grpc"
      self."opentelemetry-exporter-otlp-proto-http"
    ];
  };
  "opentelemetry-exporter-otlp-proto-common" = super.buildPythonPackage rec {
    pname = "opentelemetry-exporter-otlp-proto-common";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/4d/769f3b1b1c6af5e603da50349ba31af757897540a75d666de22d39461055/opentelemetry_exporter_otlp_proto_common-1.28.2-py3-none-any.whl";
      sha256 = "04iazwxv6ip3cql1wfp94w3hc4din1yccv1xbg1ndxklnm1ijnsl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-proto"
    ];
  };
  "opentelemetry-exporter-otlp-proto-grpc" = super.buildPythonPackage rec {
    pname = "opentelemetry-exporter-otlp-proto-grpc";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/7e/6af5a7de87988cfc951db86f7fd0ecaabc20bc112fd9cfe06b8a01f11400/opentelemetry_exporter_otlp_proto_grpc-1.28.2-py3-none-any.whl";
      sha256 = "1qlj2nidj326mrp3dzwddxp6h1qhzkap5hg7zidv7ak310qdk0v0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deprecated"
      self."googleapis-common-protos"
      self."grpcio"
      self."opentelemetry-api"
      self."opentelemetry-exporter-otlp-proto-common"
      self."opentelemetry-proto"
      self."opentelemetry-sdk"
    ];
  };
  "opentelemetry-exporter-otlp-proto-http" = super.buildPythonPackage rec {
    pname = "opentelemetry-exporter-otlp-proto-http";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/23/802b889cf8bf3e235f30fbcbaa2b3fd484fe8c76b5b4db00f00c0e9af20f/opentelemetry_exporter_otlp_proto_http-1.28.2-py3-none-any.whl";
      sha256 = "1whgv5vx974wcq2gz8nqpxz53h4iax3vln44wr5yymia44c1r4mg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deprecated"
      self."googleapis-common-protos"
      self."opentelemetry-api"
      self."opentelemetry-exporter-otlp-proto-common"
      self."opentelemetry-proto"
      self."opentelemetry-sdk"
      self."requests"
    ];
  };
  "opentelemetry-instrumentation" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/e3/ad23372525653b0221212d5e2a71bd97aae64cc35f90cbf0c70de57dfa4e/opentelemetry_instrumentation-0.49b2-py3-none-any.whl";
      sha256 = "0lfinjrz7fdm18ihvi6l9k1k5igmclf6b62jfi64mvwzxyq85mzn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-semantic-conventions"
      self."packaging"
      self."wrapt"
    ];
  };
  "opentelemetry-instrumentation-django" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation-django";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/5b/5475d91f5104891bed85f9a429b6383d1ad2a954537eb450f5df7ee2f130/opentelemetry_instrumentation_django-0.49b2-py3-none-any.whl";
      sha256 = "0qysarvz7mbi2j7ji5h5nzfbbshk2bxc9406gpwl7a54vf3yw4bh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-instrumentation-wsgi"
      self."opentelemetry-semantic-conventions"
      self."opentelemetry-util-http"
    ];
  };
  "opentelemetry-instrumentation-redis" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation-redis";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/36/44292ae478811bd618d14942b639b0afb7706db5ac2a1efd4e4860ab1e56/opentelemetry_instrumentation_redis-0.49b2-py3-none-any.whl";
      sha256 = "0j1bsdwfy4ff96gwh0z3r2clb9bhn9ammm7zsj10x6b8bsl6m5ks";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-semantic-conventions"
      self."wrapt"
    ];
  };
  "opentelemetry-instrumentation-requests" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation-requests";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/06/269cf4fcbd7be50a718f3d462207028bed1ec577d132fabe63ec63e4b100/opentelemetry_instrumentation_requests-0.49b2-py3-none-any.whl";
      sha256 = "066kxxczy7l17rpbb52b27bacaac6188grmq71xg1dwzn8i016yl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-semantic-conventions"
      self."opentelemetry-util-http"
    ];
  };
  "opentelemetry-instrumentation-wsgi" = super.buildPythonPackage rec {
    pname = "opentelemetry-instrumentation-wsgi";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/41/dab117b19836ffe1a863f25f64ec72eb7fb1fa86507273e9e0089e4ecb73/opentelemetry_instrumentation_wsgi-0.49b2-py3-none-any.whl";
      sha256 = "07djf6vvsnsbmvfl1irv7aws90my2395lwmc0b8zxr8mrhrm3zwm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-instrumentation"
      self."opentelemetry-semantic-conventions"
      self."opentelemetry-util-http"
    ];
  };
  "opentelemetry-proto" = super.buildPythonPackage rec {
    pname = "opentelemetry-proto";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/12/646f48d6d698a6df0437a22b591387440dc4888c8752d1a1300f730da710/opentelemetry_proto-1.28.2-py3-none-any.whl";
      sha256 = "031pf8m0fhvijdz4vnznj89qr8dis2c5hplic9j0hmfvb67ljdq8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "opentelemetry-sdk" = super.buildPythonPackage rec {
    pname = "opentelemetry-sdk";
    version = "1.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/8b/4f2b418496c08016d4384f9b1c4725a8af7faafa248d624be4bb95993ce1/opentelemetry_sdk-1.28.2-py3-none-any.whl";
      sha256 = "06xpbjw735a99hhv4q8qa90rax916m6vjhhlsb6f7wanjl96qcwk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."opentelemetry-api"
      self."opentelemetry-semantic-conventions"
      self."typing-extensions"
    ];
  };
  "opentelemetry-semantic-conventions" = super.buildPythonPackage rec {
    pname = "opentelemetry-semantic-conventions";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/be/6661c8f76708bb3ba38c90be8fa8d7ffe17ccbc5cbbc229334f5535f6448/opentelemetry_semantic_conventions-0.49b2-py3-none-any.whl";
      sha256 = "0m7f96b6bf3phw2sq9y3dxqx0z8fbxgd13iadhmphn59vb8f3rsi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."deprecated"
      self."opentelemetry-api"
    ];
  };
  "opentelemetry-util-http" = super.buildPythonPackage rec {
    pname = "opentelemetry-util-http";
    version = "0.49b2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/22/9128f10d1c2868ee42df7e10937d00f154a69bee87c416ca9b20a6af6c54/opentelemetry_util_http-0.49b2-py3-none-any.whl";
      sha256 = "0n5zsbv5wl9qk2lxgc8aw9byq452c4rckc0f2x1ppvkb3i8xc9g3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "24.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/ef/eb23f262cca3c0c4eb7ab1933c3b1f03d021f2c48f54763065b6f0e321be/packaging-24.2-py3-none-any.whl";
      sha256 = "0nd7a421brjgd4prm8fbs8a6bcv4n1yplgxalgs02p16rnyb3aq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pdf2image" = super.buildPythonPackage rec {
    pname = "pdf2image";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/33/61766ae033518957f877ab246f87ca30a85b778ebaad65b7f74fa7e52988/pdf2image-1.17.0-py3-none-any.whl";
      sha256 = "1qi799sgg8rqi9vk6v5cpgd39x3y0ny1nazg47zdy45qmzbmipgc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pillow"
    ];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "11.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/26/0d95c04c868f6bdb0c447e3ee2de5564411845e36a858cfd63766bc7b563/pillow-11.0.0.tar.gz";
      sha256 = "0fbpcwgiac19ap0h1qa1imsqhq6vxv8kg67zkgm3y05c4jpwpfkj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pint" = super.buildPythonPackage rec {
    pname = "pint";
    version = "0.24.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/16/bd2f5904557265882108dc2e04f18abc05ab0c2b7082ae9430091daf1d5c/Pint-0.24.4-py3-none-any.whl";
      sha256 = "0nbnzqw1qa9i0gmivb9j3caqqxp69p9w0b7qcp7ry5bjhxn94m5a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."flexcache"
      self."flexparser"
      self."platformdirs"
      self."typing-extensions"
    ];
  };
  "pip-licenses" = super.buildPythonPackage rec {
    pname = "pip-licenses";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/0a/bfaf1479d09d19f503a669d9c8e433ac59ae687fb8da1d8207eb85c5a9f4/pip_licenses-5.0.0-py3-none-any.whl";
      sha256 = "0za71vsaq29gvwcc52b61nqkwhbkna55qh0wmz8qdyryfmk3dj42";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."prettytable"
      self."tomli"
    ];
  };
  "platformdirs" = super.buildPythonPackage rec {
    pname = "platformdirs";
    version = "4.3.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/a6/bc1012356d8ece4d66dd75c4b9fc6c1f6650ddd5991e421177d9f8f671be/platformdirs-4.3.6-py3-none-any.whl";
      sha256 = "1yy39iay8fdb3c1r4gm011lla1sk1mc9fsw300wi1f4a83hpbrbk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prettytable" = super.buildPythonPackage rec {
    pname = "prettytable";
    version = "3.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/73/19/4bb9530512432774fdd7cb7c020851d4decbb811d95f86fd4f6a870a6d3e/prettytable-3.12.0-py3-none-any.whl";
      sha256 = "1k2pmhq4k09f3cf7mxrva4awzwpwqiy3sqp8sxiy7dimqk8hmjkp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wcwidth"
    ];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "5.28.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/6e/e69eb906fddcb38f8530a12f4b410699972ab7ced4e21524ece9d546ac27/protobuf-5.28.3.tar.gz";
      sha256 = "0yzg3i40p7rbr51xr72avpvn72yin5xcxybkyc0y99c0j72dpfk4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py-moneyed" = super.buildPythonPackage rec {
    pname = "py-moneyed";
    version = "3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/2b/2d87f12edc70f0d8c85148c51b57a4b8cf89e4d8ad291935a47ed1b7c52e/py_moneyed-3.0-py3-none-any.whl";
      sha256 = "1fyrfqv76zpwkkp5x2pw7623rdz90r91in4kc4clcny0k57s30wm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."babel"
      self."typing-extensions"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl";
      sha256 = "1k6gk7j4s3s7fpflxhndhsyx18ak7pkdfrd5mz0spiyq7mnjnw63";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pydyf" = super.buildPythonPackage rec {
    pname = "pydyf";
    version = "0.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/b3/4b87b0edaa7f2f94c131d01697f936748fc7f74c1ca9622ada372f7256e8/pydyf-0.10.0-py3-none-any.whl";
      sha256 = "1qqaikm182ni36yx991w3b6yfdsy1s0bazw22ng1l2bajz0bcxpg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyjwt" = super.buildPythonPackage rec {
    pname = "pyjwt";
    version = "2.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/ad/689f02752eeec26aed679477e80e632ef1b682313be70793d798c1d5fc8f/PyJWT-2.10.1-py3-none-any.whl";
      sha256 = "1jysk2ym1gdfzw359wj4wq281dfjrpgrlbqlpzgdbvxb60z1kpfw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyphen" = super.buildPythonPackage rec {
    pname = "pyphen";
    version = "0.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/ae/7919394672be4884ac8434e30be143db689b29b6e7fa0dd8eb2037af0337/pyphen-0.17.0-py3-none-any.whl";
      sha256 = "134mlm1zch5bpd60q79wjdmpayn46vdb44b7y05xgxl0mbjb5l6s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-barcode" = super.buildPythonPackage rec {
    pname = "python-barcode";
    version = "0.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/27/9b5c5bb1938d4e6b12f4c95f40ea905c11df3cd58e128e9305397b9a2697/python_barcode-0.15.1-py3-none-any.whl";
      sha256 = "11h85rlmsi94d5dlxzfxcnwvxpvancsqa321a8lc4sbklgxkcxh5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pillow"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl";
      sha256 = "0spixdl9m43lsv84wmhbnj9r6q3dnsbk9l2hypfhss8v1zskxdpp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-fsutil" = super.buildPythonPackage rec {
    pname = "python-fsutil";
    version = "0.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4f/e6/c8a2cdf34316bb96a7601ed47778818da266d4917bd9575d3a9ba46aedb7/python_fsutil-0.14.1-py3-none-any.whl";
      sha256 = "0ddh41mmx1njdd0nap545q9v7914gnmfg2nx9dkkyh7ly0iyci8d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-ipware" = super.buildPythonPackage rec {
    pname = "python-ipware";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/08/bd/ccd7416fdb30f104ddf6cfd8ee9f699441c7d9880a26f9b3089438adee05/python_ipware-3.0.0-py3-none-any.whl";
      sha256 = "0q3bwf12hx41f5q2lj1ryxraqs7lb03g8p9iz43w3z69grp6x4zw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python3-openid" = super.buildPythonPackage rec {
    pname = "python3-openid";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/a5/c6ba13860bdf5525f1ab01e01cc667578d6f1efc8a1dba355700fb04c29b/python3_openid-3.2.0-py3-none-any.whl";
      sha256 = "0szsdmrzixh51p69zcm51j12w8g7cbvsyk8b3rq8cx21w1qzf9k6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."defusedxml"
    ];
  };
  "python3-saml" = super.buildPythonPackage rec {
    pname = "python3-saml";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/14/49d9828443b58bd5cc80a454c91b0f867fbf36a24975d501945e6cb9e32f/python3_saml-1.16.0-py3-none-any.whl";
      sha256 = "039dzk3mmavwsnywkyy7zcl2xsig5qj3hjlgx4ifw0agn08pvf90";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."isodate"
      self."lxml"
      self."xmlsec"
    ];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2024.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none-any.whl";
      sha256 = "0987m8kd8ia2xzhnirrxhvfs4fprf86fazlc9g5fgympgs0w3iri";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/ed/79a089b6be93607fa5cdaedf301d7dfb23af5f25c398d5ead2525b063e17/pyyaml-6.0.2.tar.gz";
      sha256 = "0gmwggzm0j0iprx074g5hah91y2f68sfhhldq0f8crddj7ndk16m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qrcode" = super.buildPythonPackage rec {
    pname = "qrcode";
    version = "8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/ab/df8d889fd01139db68ae9e5cb5c8f0ea016823559a6ecb427582d52b07dc/qrcode-8.0-py3-none-any.whl";
      sha256 = "1cgiys8935y077qf5f9vz7vfc6gsjwqcyhmpkrq7mljs601mzh4z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pillow"
    ];
  };
  "rapidfuzz" = super.buildPythonPackage rec {
    pname = "rapidfuzz";
    version = "3.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/39/e3bcb901c2746734cd70151253bf9e61c688d3c415227b08e6fbf7eb5d7f/rapidfuzz-3.10.1.tar.gz";
      sha256 = "0yarb1k40a36f4p2afy5was9ifbq1jdyyyfw88zmp4bshinm85as";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "redis" = super.buildPythonPackage rec {
    pname = "redis";
    version = "5.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/12/f5/ffa560ecc4bafbf25f7961c3d6f50d627a90186352e27e7d0ba5b1f6d87d/redis-5.2.0-py3-none-any.whl";
      sha256 = "15vq3a06j6gm848y40xa21ncys8lphgybwsbsl4jpgxincmly5xf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-timeout"
    ];
  };
  "referencing" = super.buildPythonPackage rec {
    pname = "referencing";
    version = "0.35.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/59/2056f61236782a2c86b33906c025d4f4a0b17be0161b63b70fd9e8775d36/referencing-0.35.1-py3-none-any.whl";
      sha256 = "1pkmxqhpp6da5qwbcnj7v8r62fls3hrw21g3chf4v0b29lix79pd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."rpds-py"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/9b/335f9764261e915ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl";
      sha256 = "1inwsrhx0m16q0wa1z6dfm8i8xkrfns73xm25arcwwy70gz1qxkh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "rpds-py" = super.buildPythonPackage rec {
    pname = "rpds-py";
    version = "0.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/80/afdf96daf9b27d61483ef05b38f282121db0e38f5fd4e89f40f5c86c2a4f/rpds_py-0.21.0.tar.gz";
      sha256 = "1nx65y0g2db5ggsdy2hzb0lkihv07lw0cxryfq1yj3bdsv4phqzd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sentry-sdk" = super.buildPythonPackage rec {
    pname = "sentry-sdk";
    version = "2.19.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/6b/191ca63f05d3ecc7600b5b3abd493a4c1b8468289c9737a7735ade1fedca/sentry_sdk-2.19.0-py2.py3-none-any.whl";
      sha256 = "0nqjghm9iq251m1qn7sasghaz5bfpw6s62aa4hvi61gfkmq3n2vv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."urllib3"
    ];
  };
  "sgmllib3k" = super.buildPythonPackage rec {
    pname = "sgmllib3k";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/bd/3704a8c3e0942d711c1299ebf7b9091930adae6675d7c8f476a7ce48653c/sgmllib3k-1.0.0.tar.gz";
      sha256 = "1s8jm3dgqabgf8x96931scji679qkhvczlv3qld4qxpsicfgns3q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sqlparse" = super.buildPythonPackage rec {
    pname = "sqlparse";
    version = "0.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/13/5f6654c9d915077fae255686ca6fa42095b62b7337e3e1aa9e82caa6f43a/sqlparse-0.5.2-py3-none-any.whl";
      sha256 = "0pm5vmjmzxhq4vdzh0wxql3gr04dmcs0h8yrw71ih28ng1fci6z9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "structlog" = super.buildPythonPackage rec {
    pname = "structlog";
    version = "24.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/65/813fc133609ebcb1299be6a42e5aea99d6344afb35ccb43f67e7daaa3b92/structlog-24.4.0-py3-none-any.whl";
      sha256 = "043nmld4sl26nwvf6wqzl34a25b7sy70japxm54hgk4i1bl62zsr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tablib" = super.buildPythonPackage rec {
    pname = "tablib";
    version = "3.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/02/404b9a79578e1a3512bf3ae5e1fb0766859ccf3b55a83ab1e7ac4aeb7bed/tablib-3.5.0-py3-none-any.whl";
      sha256 = "1ndzvb416r4aj9321d5jws1gkkxf6zklb9lz57vjy1m6xjlwl8cq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markuppy"
      self."odfpy"
      self."openpyxl"
      self."pyyaml"
      self."xlrd"
      self."xlwt"
    ];
  };
  "tinycss2" = super.buildPythonPackage rec {
    pname = "tinycss2";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/34/ebdc18bae6aa14fbee1a08b63c015c72b64868ff7dae68808ab500c492e2/tinycss2-1.4.0-py3-none-any.whl";
      sha256 = "12aj9j40vnssfyjhbfab77lrdgafvzw1svhcbnqs0pb7nx3wyj9s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."webencodings"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/f7/4da0ffe1892122c9ea096c57f64c2753ae5dd3ce85488802d11b0992cc6d/tomli-2.1.0-py3-none-any.whl";
      sha256 = "14837r3vmic8n77w8izw23i1dxqfyrc38lpni7gwrxan3hyprid5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.12.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl";
      sha256 = "03bhjivpvdhn4c3x0963z89hv7b5vxr415akd1fgiwz0a41wmr84";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tzdata" = super.buildPythonPackage rec {
    pname = "tzdata";
    version = "2024.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/ab/7e5f53c3b9d14972843a647d8d7a853969a58aecc7559cb3267302c94774/tzdata-2024.2-py2.py3-none-any.whl";
      sha256 = "1kb5jpbspw46863vr3s4fhh44d1gagl5a9ccs7537pnwdiw97054";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "uritemplate" = super.buildPythonPackage rec {
    pname = "uritemplate";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c0/7461b49cd25aeece13766f02ee576d1db528f1c37ce69aee300e075b485b/uritemplate-4.1.1-py2.py3-none-any.whl";
      sha256 = "0bp08jq51nrjha3sgfc4dwk3d2cflfa5kl7alhp33pcvv6w0h343";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.2.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/d9/5f4c13cecde62396b0d3fe530a50ccea91e7dfc1ccf0e09c228841bb5ba8/urllib3-2.2.3-py3-none-any.whl";
      sha256 = "1b4g5yxarl7ib5fxvn8bkssbyrf44nm76b967vxbmcfw8fh9r2fa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.2.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/84/fd2ba7aafacbad3c4201d395674fc6348826569da3c0937e75505ead3528/wcwidth-0.2.13-py2.py3-none-any.whl";
      sha256 = "0nb89xwaqyhi09hqvnvb3hn047lgjkzjj60k6apq83alwi4919ix";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "weasyprint" = super.buildPythonPackage rec {
    pname = "weasyprint";
    version = "62.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/d1/10f4225bec3450e7c0aa5813697ce76eb2dfa1f3c5e530510253b6b276b2/weasyprint-62.3-py3-none-any.whl";
      sha256 = "08gdv9g0y3pd170zqygns9lal9pmc5536gmk6phq8l71dij4h46k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."cssselect2"
      self."fonttools"
      self."html5lib"
      self."pillow"
      self."pydyf"
      self."pyphen"
      self."tinycss2"
    ];
  };
  "webencodings" = super.buildPythonPackage rec {
    pname = "webencodings";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl";
      sha256 = "0y2aa53jkkcszhbbx59z817ywjvy3ah3lavym6bn88n2yc9i5bx0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "whitenoise" = super.buildPythonPackage rec {
    pname = "whitenoise";
    version = "6.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/3a/8d22513e1942899270dcdbd47f9886309836442cd7ede4b0d00be79715f5/whitenoise-6.8.2-py3-none-any.whl";
      sha256 = "1012bns0zi9afzjjd5xbsb34fh84y338ill1dnax2hx08zhxq4nz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/24/a1/fc03dca9b0432725c2e8cdbf91a349d2194cf03d8523c124faebe581de09/wrapt-1.17.0.tar.gz";
      sha256 = "00886b7ry1vdbvpc2wi880y563xf6y4mxwwfm1q12wvw66i7l60n";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "xlrd" = super.buildPythonPackage rec {
    pname = "xlrd";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl";
      sha256 = "1pdvy31hclmq8ddj12kbcdwjckp79glzcac12p0spnbvhy4ywcva";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "xlwt" = super.buildPythonPackage rec {
    pname = "xlwt";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl";
      sha256 = "0blbcaf1mq3xm2b1ax38maw7i0pmhp1jr4kx565a92v74h2jd0m0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "xmlsec" = super.buildPythonPackage rec {
    pname = "xmlsec";
    version = "1.3.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/5b/244459b51dfe91211c1d9ec68fb5307dfc51e014698f52de575d25f753e0/xmlsec-1.3.14.tar.gz";
      sha256 = "1nd2jbrfbmnd566i1v39xrh3a0b1nqvf5bhydywcsnw95x7q0kwk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."lxml"
    ];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/1a/7e4798e9339adc931158c9d69ecc34f5e6791489d469f5e50ec15e35f458/zipp-3.21.0-py3-none-any.whl";
      sha256 = "0cfr7hmx88sji1ai52chvj1ivlgnqnxgy96fxdhg3499zl2vw6xc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
